import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  colors,
  gradients,
  motion,
  radii,
  shadows,
  spacing,
  typography,
} from '../src/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../dist/tokens.css');

const lines: string[] = [];
lines.push('/* Generated by packages/tokens/scripts/build-css.ts — do not edit by hand. */');
lines.push(':root {');

for (const [name, scale] of Object.entries(colors)) {
  for (const [step, value] of Object.entries(scale)) {
    lines.push(`  --color-${name}-${step}: ${value};`);
  }
}

for (const [key, value] of Object.entries(spacing)) {
  lines.push(`  --spacing-${key.replace('.', '_')}: ${value};`);
}

for (const [key, value] of Object.entries(radii)) {
  lines.push(`  --radius-${key}: ${value};`);
}

for (const [key, value] of Object.entries(shadows)) {
  lines.push(`  --shadow-${key}: ${value};`);
}

for (const [key, value] of Object.entries(motion.duration)) {
  lines.push(`  --duration-${key}: ${value};`);
}
for (const [key, value] of Object.entries(motion.easing)) {
  lines.push(`  --ease-${key}: ${value};`);
}

for (const [key, value] of Object.entries(gradients)) {
  lines.push(`  --gradient-${key}: ${value};`);
}

lines.push(`  --font-sans: ${typography.fontFamily.sans};`);
lines.push(`  --font-mono: ${typography.fontFamily.mono};`);
lines.push(`  --font-display: ${typography.fontFamily.display};`);

lines.push('}');
lines.push('');

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'), 'utf8');
console.info(`✓ wrote ${outPath}`);
